@startuml
title как пользователь взаимодействует с api

actor пользователь as user
participant браузер as browser
participant сервер as server
participant маршрутизатор as router
participant контроллер_upload_api as controller


activate user
user -> browser: Enters url (api/v1/upload/image/save?key=api_key)
activate browser
browser -> server: send request
activate server
server -> router: sends url to router
router -> controller: Finds and calls the matching controller
controller --> server: executes handler and saves result
server --> browser: sends result
browser --> user: displays result

@enduml
